apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: vendor
  contents:
  - path: github.com/cloudfoundry/cf-for-k8s
    git:
      url: https://github.com/cloudfoundry/cf-for-k8s
      ref: 5e97f4786b7a540c74f83f23812dec1f5b0008b4
    includePaths:
    - config/**/*
    - config-optional/use-external-dns-for-wildcard.yml
