apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: vendor
  contents:
  - path: github.com/cloudfoundry/cf-for-k8s
    git:
      url: https://github.com/cloudfoundry/cf-for-k8s
      ref: c40f770098b3269c2f7203f4dbb67817255eaa23
    includePaths:
    - config/**/*
    - config-optional/use-external-dns-for-wildcard.yml
