apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: vendor
  contents:
  - path: github.com/cloudfoundry/cf-for-k8s
    git:
      url: https://github.com/cloudfoundry/cf-for-k8s
      ref: 64ec279b4a0a7b46668cfe6e639d6f6b36cf536a
    includePaths:
    - config/**/*
    - config-optional/use-external-dns-for-wildcard.yml
