apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: vendor
  contents:
  - path: .
    git:
      url: https://github.com/cloudfoundry/cf-for-k8s
      ref: a1027bb173e710bb011e883da83ea2ec906985f8
    includePaths:
    - config-optional/use-external-dns-for-wildcard.yml
