apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: minio-cert
  namespace: ${namespace}
spec:
  dnsNames:
  - '${minio_domain}'
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: minio-tls-secret